################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-redV3:
    image: nodered/node-red:3.0.2
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    networks:
      - keller
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  keller:
    external: true
